### PR TITLE
Assorted Smirnov-Grubbs test enhancements

### PR DESCRIPTION
**Pull request by lukius**
The following features were added:

 * Support for one-sided (min/max) tests.
 * Test output is now more flexible: the user can run the test in order to find the outliers themselves or the indices of the outliers, and not just the outlier-free data.
 * README was extended and improved.
 * Test suite was enhanced; it now covers full runs of the Smirnov-Grubbs test.
 * Japanese comments were translated to English so as to reach a greater audience.

### CODE REVIEW

**Comment by c-bata** [comment]
awesome!

**Comment by c-bata** [comment]
Hi @lukius, thank you for your nice pull request!
I just released new version of this package.

**Comment by lukius** [comment]
Glad to collaborate and improve useful scientific tools like this one. AFAIK, there is no other open-source alternative in Python. Thanks!

**Comment by lukius** [comment]
The changes log seems outdated. Maybe you can copy & paste the body of the pull request there --I don't mind being mentioned as well :smile:

**Pull request merged**
